/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.marlonflorencio.nifi.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class Entrega extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -549664216281296334L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Entrega\",\"namespace\":\"com.github.marlonflorencio.nifi.data.model\",\"fields\":[{\"name\":\"endereco\",\"type\":\"string\"},{\"name\":\"numero\",\"type\":\"string\"},{\"name\":\"cidade\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Entrega> ENCODER =
      new BinaryMessageEncoder<Entrega>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Entrega> DECODER =
      new BinaryMessageDecoder<Entrega>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Entrega> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Entrega> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Entrega> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Entrega>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Entrega to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Entrega from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Entrega instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Entrega fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public CharSequence endereco;
  @Deprecated public CharSequence numero;
  @Deprecated public CharSequence cidade;
  @Deprecated public CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Entrega() {}

  /**
   * All-args constructor.
   * @param endereco The new value for endereco
   * @param numero The new value for numero
   * @param cidade The new value for cidade
   * @param status The new value for status
   */
  public Entrega(CharSequence endereco, CharSequence numero, CharSequence cidade, CharSequence status) {
    this.endereco = endereco;
    this.numero = numero;
    this.cidade = cidade;
    this.status = status;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return endereco;
    case 1: return numero;
    case 2: return cidade;
    case 3: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: endereco = (CharSequence)value$; break;
    case 1: numero = (CharSequence)value$; break;
    case 2: cidade = (CharSequence)value$; break;
    case 3: status = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'endereco' field.
   * @return The value of the 'endereco' field.
   */
  public CharSequence getEndereco() {
    return endereco;
  }


  /**
   * Sets the value of the 'endereco' field.
   * @param value the value to set.
   */
  public void setEndereco(CharSequence value) {
    this.endereco = value;
  }

  /**
   * Gets the value of the 'numero' field.
   * @return The value of the 'numero' field.
   */
  public CharSequence getNumero() {
    return numero;
  }


  /**
   * Sets the value of the 'numero' field.
   * @param value the value to set.
   */
  public void setNumero(CharSequence value) {
    this.numero = value;
  }

  /**
   * Gets the value of the 'cidade' field.
   * @return The value of the 'cidade' field.
   */
  public CharSequence getCidade() {
    return cidade;
  }


  /**
   * Sets the value of the 'cidade' field.
   * @param value the value to set.
   */
  public void setCidade(CharSequence value) {
    this.cidade = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public CharSequence getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new Entrega RecordBuilder.
   * @return A new Entrega RecordBuilder
   */
  public static Builder newBuilder() {
    return new Builder();
  }

  /**
   * Creates a new Entrega RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Entrega RecordBuilder
   */
  public static Builder newBuilder(Builder other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * Creates a new Entrega RecordBuilder by copying an existing Entrega instance.
   * @param other The existing instance to copy.
   * @return A new Entrega RecordBuilder
   */
  public static Builder newBuilder(Entrega other) {
    if (other == null) {
      return new Builder();
    } else {
      return new Builder(other);
    }
  }

  /**
   * RecordBuilder for Entrega instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Entrega>
    implements org.apache.avro.data.RecordBuilder<Entrega> {

    private CharSequence endereco;
    private CharSequence numero;
    private CharSequence cidade;
    private CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.endereco)) {
        this.endereco = data().deepCopy(fields()[0].schema(), other.endereco);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.numero)) {
        this.numero = data().deepCopy(fields()[1].schema(), other.numero);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.cidade)) {
        this.cidade = data().deepCopy(fields()[2].schema(), other.cidade);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Entrega instance
     * @param other The existing instance to copy.
     */
    private Builder(Entrega other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.endereco)) {
        this.endereco = data().deepCopy(fields()[0].schema(), other.endereco);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numero)) {
        this.numero = data().deepCopy(fields()[1].schema(), other.numero);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.cidade)) {
        this.cidade = data().deepCopy(fields()[2].schema(), other.cidade);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.status)) {
        this.status = data().deepCopy(fields()[3].schema(), other.status);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'endereco' field.
      * @return The value.
      */
    public CharSequence getEndereco() {
      return endereco;
    }


    /**
      * Sets the value of the 'endereco' field.
      * @param value The value of 'endereco'.
      * @return This builder.
      */
    public Builder setEndereco(CharSequence value) {
      validate(fields()[0], value);
      this.endereco = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'endereco' field has been set.
      * @return True if the 'endereco' field has been set, false otherwise.
      */
    public boolean hasEndereco() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'endereco' field.
      * @return This builder.
      */
    public Builder clearEndereco() {
      endereco = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'numero' field.
      * @return The value.
      */
    public CharSequence getNumero() {
      return numero;
    }


    /**
      * Sets the value of the 'numero' field.
      * @param value The value of 'numero'.
      * @return This builder.
      */
    public Builder setNumero(CharSequence value) {
      validate(fields()[1], value);
      this.numero = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'numero' field has been set.
      * @return True if the 'numero' field has been set, false otherwise.
      */
    public boolean hasNumero() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'numero' field.
      * @return This builder.
      */
    public Builder clearNumero() {
      numero = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'cidade' field.
      * @return The value.
      */
    public CharSequence getCidade() {
      return cidade;
    }


    /**
      * Sets the value of the 'cidade' field.
      * @param value The value of 'cidade'.
      * @return This builder.
      */
    public Builder setCidade(CharSequence value) {
      validate(fields()[2], value);
      this.cidade = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'cidade' field has been set.
      * @return True if the 'cidade' field has been set, false otherwise.
      */
    public boolean hasCidade() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'cidade' field.
      * @return This builder.
      */
    public Builder clearCidade() {
      cidade = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public CharSequence getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public Builder setStatus(CharSequence value) {
      validate(fields()[3], value);
      this.status = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public Builder clearStatus() {
      status = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Entrega build() {
      try {
        Entrega record = new Entrega();
        record.endereco = fieldSetFlags()[0] ? this.endereco : (CharSequence) defaultValue(fields()[0]);
        record.numero = fieldSetFlags()[1] ? this.numero : (CharSequence) defaultValue(fields()[1]);
        record.cidade = fieldSetFlags()[2] ? this.cidade : (CharSequence) defaultValue(fields()[2]);
        record.status = fieldSetFlags()[3] ? this.status : (CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Entrega>
    WRITER$ = (org.apache.avro.io.DatumWriter<Entrega>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Entrega>
    READER$ = (org.apache.avro.io.DatumReader<Entrega>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.endereco);

    out.writeString(this.numero);

    out.writeString(this.cidade);

    out.writeString(this.status);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.endereco = in.readString(this.endereco instanceof Utf8 ? (Utf8)this.endereco : null);

      this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);

      this.cidade = in.readString(this.cidade instanceof Utf8 ? (Utf8)this.cidade : null);

      this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.endereco = in.readString(this.endereco instanceof Utf8 ? (Utf8)this.endereco : null);
          break;

        case 1:
          this.numero = in.readString(this.numero instanceof Utf8 ? (Utf8)this.numero : null);
          break;

        case 2:
          this.cidade = in.readString(this.cidade instanceof Utf8 ? (Utf8)this.cidade : null);
          break;

        case 3:
          this.status = in.readString(this.status instanceof Utf8 ? (Utf8)this.status : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










